#!/bin/bash
# Configure passwordless sudo for OptiMac safe commands
# Run: sudo ./scripts/setup-sudo.sh

set -e

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run with sudo"
    echo "Usage: sudo ./scripts/setup-sudo.sh"
    exit 1
fi

CURRENT_USER="${SUDO_USER:-$(logname)}"

cat > /etc/sudoers.d/optimac << EOF
# OptiMac MCP Server - passwordless sudo for safe system commands
# Generated by OptiMac installer

$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/sbin/purge
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/mdutil
$CURRENT_USER ALL=(ALL) NOPASSWD: /sbin/route -n flush
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/dscacheutil -flushcache
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/pmset
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/killall -HUP mDNSResponder
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/powermetrics
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/sbin/networksetup
$CURRENT_USER ALL=(ALL) NOPASSWD: /bin/rm -rf /tmp/*
EOF

chmod 440 /etc/sudoers.d/optimac

# Validate
visudo -c -f /etc/sudoers.d/optimac

echo "[OK] Passwordless sudo configured for user: $CURRENT_USER"
echo ""
echo "OptiMac can now run these commands without password prompts:"
echo "  - purge (memory)"
echo "  - mdutil (Spotlight)"
echo "  - route flush (network)"
echo "  - dscacheutil (DNS)"
echo "  - pmset (power)"
echo "  - killall mDNSResponder (DNS restart)"
echo "  - powermetrics (thermal monitoring)"
echo "  - networksetup (DNS servers)"
echo "  - rm /tmp/* (temp cleanup)"
